package com.company.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.ArrayList;
import java.util.List;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "building")
public class Building {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String buildingId;

    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute
    private String location;

    @DynamoDBAttribute
    private List<String> elevatorIds = new ArrayList<>();
}
