package com.company.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;
import java.util.ArrayList;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "elevator")
public class Elevator {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String elevatorId;

    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute
    private List<Integer> floors = new ArrayList<>();

    @DynamoDBAttribute
    private int currentFloor;

    @DynamoDBAttribute
    private ElevatorState elevatorState;

    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute(attributeName = "elevatorState")
    public ElevatorState getElevatorState() {
        return elevatorState;
    }

}
